from typing import AsyncIterator, Dict, List, Protocol, Tuple, Union

Json = Union[int, float, str, bool, Dict, List, None]


class StorageProtocol(Protocol):

    async def close(self) -> None: ...

    async def set(self, key: str, value: Json = None) -> None: ...

    async def get(self, key: str) -> Json: ...

    async def delete(self, key: str) -> None: ...

    def iterate(self, prefix: str = '') -> AsyncIterator[Tuple[str, Json]]: ...

    async def clear(self) -> None: ...
